version: "3.3"

services:
  etcd1:
    network_mode: "host"
    image: bitnami/etcd:3
    volumes:
    - ./testdata/certs:/certs
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=node1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=https://node1.local:2380
      - ETCD_LISTEN_PEER_URLS=https://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=https://node1.local:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=node1=https://node1.local:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_PEER_CLIENT_CERT_AUTH=true
      - ETCD_PEER_TRUSTED_CA_FILE=/certs/root_ca.crt
      - ETCD_PEER_CERT_FILE=/certs/etcd/peer.pem
      - ETCD_PEER_KEY_FILE=/certs/etcd/peer.key
      - ETCD_CLIENT_CERT_AUTH=true
      - ETCD_TRUSTED_CA_FILE=/certs/root_ca.crt
      - ETCD_CERT_FILE=/certs/etcd/server.pem
      - ETCD_KEY_FILE=/certs/etcd/server.key
    ports:
      - 2379:2379